### ISSUE TITLE
698644 - Reinforce the Line + defending buff/debuff aren't visible 

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar-FE#114]
- It's impossible to know which attack action cards to target with Rout (The same issue can come up with Shred for example)
The React UI shows that you can click on the Defense icon, but it does nothing when you click on it.

![image](https://user-images.githubusercontent.com/26232486/216953569-f04085af-a204-4cfe-b503-d17fc275aaeb.png)
![image](https://user-images.githubusercontent.com/26232486/216953037-bb44f9b1-bca4-4fd5-94fd-3a9287d6f059.png)

**Comment by LaustinSpayce** [comment]
I think i need information from the be to highlight the cards and know what to send when you click on them.
