### ISSUE TITLE
On my screen the action tracker gem is off

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar-FE#116]
![image](https://user-images.githubusercontent.com/26232486/216995050-267efd1d-d307-4215-bd35-a61851d36b39.png)

**Comment by LaustinSpayce** [comment]
Just in this one position or throughout? What browser you using? What was going on at the time? It helps to not be vague when writing issues

**Comment by PvtVoid** [comment]
Every position, Firefox, and any game I open its offset no matter what's happening

![image](https://user-images.githubusercontent.com/26232486/217028787-68b74720-0f78-4db7-80d2-8153f4647d68.png)
![image](https://user-images.githubusercontent.com/26232486/217028914-59fd6772-319a-4adb-b192-acc088beeacd.png)
