### ISSUE TITLE
Some improvements and feedback from Legacy Talishar is missing - Pitch Stack + Playable cards from Banish

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar-FE#118]
Some good feedback we received last year and that was unanimously was how hard it is to play against Kano. 2 things were done to improve the player's capacity to follow what Kano is doing. (Also Shadow heroes but less relevant as Chane CC is LL and Levia play less with recursion)

1. Show playable cards from the banish zone. Currently, this isn't on the React Client.
2. Show Pitch stack so it's easier to follow what's being pitched by the players.

They are 2 improvements that improved a lot of the QoL on Talishar and I believe the react client would benefit from having those also.

![image](https://user-images.githubusercontent.com/26232486/216995744-5b8d8e3d-91bd-4684-b6a8-14070816650a.png)

**Comment by LaustinSpayce** [comment]
We should have show playable banish cards active in the FE already but not sure if only when spectating. Might need some band end effort to send the info over so it can be displayed properly. Or maybe for added visibility they can be “permanents” strewn in the permanents section in front like in the many live games we saw at the time.

the pitch modification was fine and I can see people wanting to have it back. For this interface we have everything in its “place” and am trying to avoid the overlapping mis-sized inconsistent placements that the developers of the old ui had. I do have some idea for the pitch. I will see if it could be revisited in a new way.
