### ISSUE TITLE
FE needs to support new Quiver card type

### ISSUE THREAD

**Issue by OotTheMonk** [Talishar/Talishar-FE#128]
See revisions df418ca9 and 759cb4b6 for the new things passed up to the BE and passed down from the BE for the quiver (basically just a new quiver property -- it's separate from hands because as far as I can tell it is separate from hands in the rules. You could theoretically have a 1H bow and still a quiver).

**Comment by LaustinSpayce** [comment]
We need to see if this should be handled as "hand equipment" because it sits in that zone. Or if I have to make some weird special logic path *just* for quivers. I think the most straightforward way to implement it is to be hand held equipment that uses 0 hands.
