### ISSUE TITLE
Once you close the end game stats window you can't reopen it

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar-FE#135]
As title

**Comment by OotTheMonk** [comment]
LITERALLY UNUSABLE, PLZ FIX

**Comment by OotTheMonk** [comment]
I can't even

**Comment by LaustinSpayce** [comment]
https://discord.com/channels/865412150125789214/971928581267664936/1091776038738071562

We should adjust the end game display to fit on one screen for a screenshot on a desktop.

This might lead to a bigger discussion now as to wether we need to retire parts of picocss already.
