### ISSUE TITLE
Cards with blood debt are not always playable from Banish (Levia OP now)

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar-FE#161]
<img width="484" alt="image" src="https://user-images.githubusercontent.com/5060535/219697347-f8c3b824-3a36-4d3c-a432-741484206904.png">

Just because a blood debt card is banished, you can't play it.

I just tested this, I can play shadow brute cards from the banish zone.

**Comment by OotTheMonk** [comment]
![image](https://user-images.githubusercontent.com/77394768/219878328-0e6e6488-0be3-494e-8fe5-dfae13fd7ad9.png)
