### ISSUE TITLE
[React UI] Highlight specific effects 

### ISSUE THREAD

**Issue by Tchamber5** [Talishar/Talishar-FE#193]
9/10

when mulitiple could apply	multiple effects on one card (preferably clarified on the section on the 'opponents effect' section) for cards such as voltaire	

Mentions: 1	

https://discord.com/channels/865412150125789214/971928581267664936/1018372140191469578

**Comment by OotTheMonk** [comment]
Sending to FE repo; still needs react FE changes. Not adding this on legacy FE.

**Comment by LaustinSpayce** [comment]
@OotTheMonk can I check with you again what numUses means, exactly?
