### ISSUE TITLE
End of Turn and other phase images shouldn't be showing a hover when hovering them. It currently shows that an images is missing

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar-FE#210]
![image](https://user-images.githubusercontent.com/26232486/223707725-8e3b94c7-1b44-4282-bd16-e7e51af14350.png)

**Comment by PvtVoid** [comment]
I'm curious if you had time to check this :) I saw it happen today again and it's a long-lasting bug. The code was already there in Legacy and could be simply reimplemented I'm sure it's a quick fix :) If you have any questions let me know.

**Comment by OotTheMonk** [comment]
As I'm sure you can imagine, the code is quite different from the legacy client so it is not possible to simply copy the code over. If you have a quick fix, you are welcome to submit a pull request. Right now we are busy with implementing cards from the new sets.

**Comment by PvtVoid** [comment]
I don't have the brain capacity or time with the newborn. Maybe in couple of months if it's still there and my life is stable 😅

**Comment by PvtVoid** [comment]
> As I'm sure you can imagine, the code is quite different from the legacy client so it is not possible to simply copy the code over. If you have a quick fix, you are welcome to submit a pull request. Right now we are busy with implementing cards from the new sets.

Done, please double-check that it's good. It worked for me locally. It was literally to copy the code over.
