### ISSUE TITLE
React Feedback and current issue

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar-FE#211]
### I don't know what is known and what is been worked on but here are some issues I saw. Feel free to use some of those improvements if you want. No need to justify yourself if there's stuff you don't want to do or want to ignore 😄 

The Manual Mode setting appears twice in the menu and neither is functional.

![image](https://user-images.githubusercontent.com/26232486/223727768-101e5f2d-920b-4ecf-9fb6-643c075094b1.png)

**Comment by PvtVoid** [comment]
Full Control should be a toggle. It shows as a button on my screen
![image](https://user-images.githubusercontent.com/26232486/223728326-c66b55e1-fb75-44c8-b911-3c12a3560d8b.png)

**Comment by PvtVoid** [comment]
None of the settings seems functional. At least when I click any of those 8 options the choice isn't kept in memory and it's cleared every time I reopen the menu.

![image](https://user-images.githubusercontent.com/26232486/223728914-88ca7ebd-8d27-4ab1-a512-5f15a09c090b.png)

**Comment by PvtVoid** [comment]
Defence Phase isn't a phase or a step in Flesh and Blood. I think you should change it to Defend Step

![image](https://user-images.githubusercontent.com/26232486/223729415-1e045787-2918-4087-bd8a-467c1c322cbb.png)
![image](https://user-images.githubusercontent.com/26232486/223729238-dc1f759c-a882-4dfe-a2a2-d844295ce8c8.png)

**Comment by PvtVoid** [comment]
Same thing with Defence Reaction Step. It's only called the Reaction Step

![image](https://user-images.githubusercontent.com/26232486/223729827-49fd6a6e-7f2c-419d-8092-9f202b8355eb.png)
![image](https://user-images.githubusercontent.com/26232486/223729674-c1b6d751-2c09-43a9-980c-8ce75689ecfc.png)

**Comment by PvtVoid** [comment]
The icons for Go Again/Dominate are really small. I do believe it could be bigger. I really like the Go Again icon. I think the Dominate icon could use some work. A circle doesn't really show what it means compared to the legacy version that really jumps in your face.

![image](https://user-images.githubusercontent.com/26232486/223730998-2dd29aa4-ba52-4ad9-9479-492f5c6a2315.png)
![image](https://user-images.githubusercontent.com/26232486/223730792-448a0aa5-5ca3-4bc4-a981-102a1b43dd30.png)
![image](https://user-images.githubusercontent.com/26232486/223730538-ce9c693c-18c8-4cd5-b5d9-be94616d8ec2.png)

**Comment by PvtVoid** [comment]
Your permanent gets partially hidden (x3 on runechants). Not sure if it's a local resolution thing or like that for everyone.

![image](https://user-images.githubusercontent.com/26232486/223732921-a820118a-2144-4804-81b2-26cbbb1a4751.png)

**Comment by PvtVoid** [comment]
Main Phase doesn't exist in Flesh and Blood. It is an MTG term and could also be improved for Flesh and Blood term.

![image](https://user-images.githubusercontent.com/26232486/223733450-eb003ec7-ab28-499e-9dcb-a40e8ceebc28.png)

**Comment by PvtVoid** [comment]
> Hey thanks for these and good shout on the steps. The Options are currently a WIP and not finished so they'll be done eventually./

Yeah I know it's a work in progress, just thought I would share some feedback. I keep in my mind that it's a WIP and don't worry about justifying yourself. You do it when you have time, but at least it'll be known as maybe you didn't know :)

**Comment by LaustinSpayce** [comment]
A few of these are really easy and I put them in already as it's just a change in wording:
`function phaseTitle(turnPhase: string | undefined) {
  switch (turnPhase) {
    case 'M':
      return 'Action Phase';
    case 'B':
      return 'Defend Step';
    case 'A':
      return 'Reaction Step';
    case 'D':
      return 'Reaction Step';
    case 'P':
      return 'Pitching';
    case 'ARS':
      return 'End Phase';
    case 'PDECK':
      return 'End Phase';
    default:
      return null;
  }`

**Comment by PvtVoid** [comment]
I personally feel like this area is what I dislike the most. A lot of colours and a lot of style mismatch is happening. It feels overwhelming and less Polish than the nice pop-up and the rest of the react client. Maybe it's just me 

![image](https://user-images.githubusercontent.com/26232486/223733883-a1b1d7e1-b1da-4df0-8be6-23d04cde8238.png)

**Comment by PvtVoid** [comment]
> A few of these are really easy and I put them in already as it's just a change in wording:
> 
> ```
> function phaseTitle(turnPhase: string | undefined) {
>   switch (turnPhase) {
>     case 'M':
>       return 'Action Phase';
>     case 'B':
>       return 'Defend Step';
>     case 'A':
>       return 'Reaction Step';
>     case 'D':
>       return 'Reaction Step';
>     case 'P':
>       return 'Pitching';
>     case 'ARS':
>       return 'End Phase';
>     case 'PDECK':
>       return 'End Phase';
>     default:
>       return null;
>   }
> ```

You only forgot the End Step instead of End Phase 😄

**Comment by LaustinSpayce** [comment]
> > A few of these are really easy and I put them in already as it's just a change in wording:
> > ```
> > function phaseTitle(turnPhase: string | undefined) {
> >   switch (turnPhase) {
> >     case 'M':
> >       return 'Action Phase';
> >     case 'B':
> >       return 'Defend Step';
> >     case 'A':
> >       return 'Reaction Step';
> >     case 'D':
> >       return 'Reaction Step';
> >     case 'P':
> >       return 'Pitching';
> >     case 'ARS':
> >       return 'End Phase';
> >     case 'PDECK':
> >       return 'End Phase';
> >     default:
> >       return null;
> >   }
> > ```
> 
> You only forgot the End Step instead of End Phase 😄

That's why you need a judge to correct these things.

Re the Combat Chain, I'm not 100% happy with the colours textures etc on it, I do want to draw attention to it (as it's where most the stuff is happening) - Right now I do consider it "good enough", it's not too difficult to rework these components down the line (which is a big reason why we're doing the front end. Just ideally need someone who's actually good at UI/UX to help us out.

**Comment by PvtVoid** [comment]
the shortcut for undo "U" seems to not be working on the React FE. Not sure if it was a design choice or if it wasn't coded. I personally prefer that then clicking (Although it's better in react having access to the undo button a lot closer)
