### ISSUE TITLE
Arsenal face up/down icon not needed for opponent's arsenal

### ISSUE THREAD

**Issue by OotTheMonk** [Talishar/Talishar-FE#215]
Super low priority
![image](https://user-images.githubusercontent.com/77394768/224505763-34f3ee3c-5b85-483a-a7f5-733d57137c87.png)

**Comment by LaustinSpayce** [comment]
Also is #209 so I'll close the other one

**Comment by LaustinSpayce** [comment]
I had a go at this it's actually a minor pain in the butt to do.
