### ISSUE TITLE
u hotkey doesn't work for undo

### ISSUE THREAD

**Issue by OotTheMonk** [Talishar/Talishar-FE#244]

**Comment by LaustinSpayce** [comment]
I'd suggest Z for undo (ctrl+z, cmd+z in literally every other program on earth)

**Comment by LaustinSpayce** [comment]
We can also have both

**Comment by LaustinSpayce** [comment]
![the-road-to-el-dorado-both](https://user-images.githubusercontent.com/5060535/229302670-e8a09ba5-1c52-4815-a7d8-ed853495af07.gif)

**Comment by OotTheMonk** [comment]
I tried to implement this, but was unable to :( Let me know if you are able to get it to work, I'd be curious to know
