### ISSUE TITLE
Make opponent's card more like 40% of available space since not as much clarity of information is needed for their stuff

### ISSUE THREAD

**Issue by OotTheMonk** [Talishar/Talishar-FE#249]
![image](https://user-images.githubusercontent.com/77394768/229302592-24fe7877-2d85-4af4-a74c-8bfc63885389.png)

**Comment by OotTheMonk** [comment]
We talked about this earlier, actually I think it might be even better to reduce the size of _all_ the cards in play to add more focus on the players' hands and the combat chain.

**Comment by clarkd23** [comment]
We can close this issue.
