### ISSUE TITLE
Display temporary buffs to weapons and cards

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar-FE#29]
Some way to show temporary (or even permanent) buffs to weapons and cards is needed. Or even if a weapon just has some ability baked in like Boost/Go Again etc

This would make cards like Blood on Her Hands much easier to use because you can see which card already has Go Again etc.

This will require more info to be sent to the FE from the BE.

https://github.com/Talishar/Talishar/issues/119

**Comment by LaustinSpayce** [comment]
This could be quite involved with extra data needed from BE so don't have as part of Phase 1 of rollout

**Comment by PvtVoid** [comment]
Fixed with https://github.com/Talishar/Talishar/pull/790

**Comment by PvtVoid** [comment]
Feel free to reopen the issue if you want to work on the FE of thing and improve it.
