### ISSUE TITLE
Prompt "are you sure?" If people will pass and leave their arsenal empty.

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar-FE#297]
https://discord.com/channels/865412150125789214/971928581267664936/1094381464830881953

> New Client doesn't stop you from passing when you can arsenal, any chance this can be added back?

**Comment by OotTheMonk** [comment]
Partial fix added this to experimental mode; still need to fix the window to not go behind the "what do you need to do" banner

**Comment by OotTheMonk** [comment]
See commit 98b54608
