### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar-FE#32]
Add keyboard shortcuts aside from spacebar/pass.

Option 1) Keep same as current talishar
Option 2) Focus on wasd side of the keyboard

Advanced Option 3) have it customisable

**Comment by tetsuo-matsumura** [comment]
Hey @LaustinSpayce, I'm exploring this issue and I couldn't find any reference for the current shortcuts.
Could you describe where to find it?
Thanks!

**Comment by LaustinSpayce** [comment]
![EDAFF1BA-670D-4772-B3D6-20E67A8401F4](https://user-images.githubusercontent.com/5060535/214456633-5270ae73-3e02-471e-a22c-f4e2a4d6f3d9.jpeg)

the only documentation we have is from the original BE client.
The current active shortcut in the ui is attached to the pass turn widget / player health widget.

**Comment by LaustinSpayce** [comment]
I am considering adopting a similar keyboard shortcut style that is used by Felt Table, the cards can be played using 1 2 3 4 etc. We could also take a liberty in having the keys bunched up on the left side of the keyboard I guess so people could use one hand for the shortcuts without bouncing up and down the keyboard too much.
