### ISSUE TITLE
[Bug] - Lots of empty Backend Warning popup after match ended

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar-FE#426]
They just keep happening and showing up. Not sure why. Game #2534809
<img width="407" alt="image" src="https://github.com/Talishar/Talishar-FE/assets/26232486/b93eb915-558e-4540-8f6e-f8667015f81b">

**Comment by LaustinSpayce** [comment]
Cannot repro, I think something else fixed it, if can repro then can reopen

**Comment by OotTheMonk** [comment]
Did you delete the file on the server?

**Comment by PvtVoid** [comment]
This is not a bug that happened to me recently. I haven't had this bug happen again since I reported it 👍
