### ISSUE TITLE
Deck Validation doesn't care about the hero amount of hands - Kayo can equip 2x 1H weapons

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar-FE#474]
I feel like this code should have stayed in the BE. I try to fix it, but didn't manage.

![image](https://github.com/Talishar/Talishar-FE/assets/26232486/1d01f26b-a352-4354-8ed5-e51c2deb1238)
![image](https://github.com/Talishar/Talishar-FE/assets/26232486/0da83919-c476-404e-97b0-f7200decb3f1)

**Comment by LaustinSpayce** [comment]
Validation is done in the FE as well as the BE to be more convenient to the user. BE is still the final authority on whether the deck is valid or not.

**Comment by PvtVoid** [comment]
Fixed with https://github.com/Talishar/Talishar-FE/pull/509/commits/691bcb416c0ab8b18fea6cdd01ede60bd34de5e5
