### ISSUE TITLE
Show/Hide Priority Pop Up

### ISSUE THREAD

**Issue by Tchamber5** [Talishar/Talishar-FE#78]
I think a show/hide button on the priority pop up windows could be very handy. So when Vis pops 18 runechants you can hide the window to look at the board before deciding what to do as an example

Mentions: 6

https://discord.com/channels/865412150125789214/971928581267664936/1017071410516086794

**Comment by OotTheMonk** [comment]
I think this might already be planned for react-fe, moving to that repo. Close if duplicate.

**Comment by LaustinSpayce** [comment]
Yeah this needs to be implemented, been on the roadmap a long time.
