### ISSUE TITLE
Double face ally cards cannot be check when hovering

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar-FE#79]
Show both sides of DFC when you hover above the invocations (UPR009 -> UPR0017): 
https://discord.com/channels/865412150125789214/971928581267664936/992124188661919866

**Comment by OotTheMonk** [comment]
Moving to react-fe repo, not going to add this to old FE.

**Comment by LaustinSpayce** [comment]
We already show DFC both sides in FE. It's a little jank, but it works!
